export const ROLES = {
  PATIENT: "patient",
  MEDECIN: "medecin",
  ADMIN: "admin",
};

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  OTP: "/otp",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  PATIENT_DASHBOARD: "/patient/dashboard",
  PATIENT_APPOINTMENTS: "/patient/rendez-vous",
  PATIENT_DOSSIER: "/patient/dossier",
  PATIENT_ORDONNANCES: "/patient/ordonnances",
  PATIENT_PROFILE: "/patient/profil",
  MEDECIN_DASHBOARD: "/medecin/dashboard",
  MEDECIN_PATIENTS: "/medecin/patients",
  MEDECIN_CONSULTATIONS: "/medecin/consultations",
  MEDECIN_ORDONNANCES: "/medecin/ordonnances",
  MEDECIN_PLANNING: "/medecin/planning",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_USERS: "/admin/utilisateurs",
  ADMIN_PATIENTS: "/admin/patients",
  ADMIN_MEDECINS: "/admin/medecins",
  ADMIN_APPOINTMENTS: "/admin/rendez-vous",
  ADMIN_STATS: "/admin/statistiques",
  ADMIN_AUDIT: "/admin/audit",
  NOT_FOUND: "/404",
  FORBIDDEN: "/403",
  SERVER_ERROR: "/500",
};